/**
 * Problem: Find the Difference
 * LeetCode Link: https://leetcode.com/problems/find-the-difference/
 * Description: You are given two strings s and t. String t is generated by random shuffling string s and then add one more letter at a random position. Return the letter that was added to t.
 */

#include <stdio.h>
#include <string.h>

char findTheDifference(char* s, char* t) {
    // Method: XOR all characters
    // The XOR sum of all characters in s and t will result in the extra character in t.
    char result = 0;
    int i;

    for (i = 0; s[i] != '\0'; i++) {
        result ^= s[i];
    }

    for (i = 0; t[i] != '\0'; i++) {
        result ^= t[i];
    }

    return result;

    /*
    // Alternative Method: Summation
    int sum_s = 0;
    int sum_t = 0;

    for (int i = 0; s[i] != '\0'; i++) {
        sum_s += s[i];
    }

    for (int i = 0; t[i] != '\0'; i++) {
        sum_t += t[i];
    }

    return (char)(sum_t - sum_s);
    */
}

// Example usage
int main() {
    printf("s=\"abcd\", t=\"abcde\", Difference: %c\n", findTheDifference("abcd", "abcde")); // Expected: e
    printf("s=\"a\", t=\"aa\", Difference: %c\n", findTheDifference("a", "aa"));           // Expected: a
    printf("s=\"ae\", t=\"aea\", Difference: %c\n", findTheDifference("ae", "aea"));       // Expected: a

    return 0;
}
